# Generated by Django 3.1.7 on 2021-04-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_orders',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
