# Generated by Django 3.1.7 on 2021-04-19 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_user_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_orders',
        ),
    ]
