# Generated by Django 3.1.7 on 2021-04-07 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniatures', '0003_subcategory_friendly_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='category',
            new_name='parent_category',
        ),
    ]
