# Generated by Django 3.1.7 on 2021-04-08 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miniatures', '0005_auto_20210407_1240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.RemoveField(
            model_name='miniature',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='miniature',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='miniature',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='miniature',
            name='army',
            field=models.CharField(default='army', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='miniature',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='miniature',
            name='faction',
            field=models.CharField(default='faction', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='miniature',
            name='gaming_system',
            field=models.CharField(default='gaming system', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='miniature',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='miniatures.category'),
        ),
        migrations.AlterField(
            model_name='miniature',
            name='date_added',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
