# Generated by Django 3.1.7 on 2021-04-08 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniatures', '0007_auto_20210408_1242'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Manufacturer',
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={},
        ),
    ]
