# Generated by Django 3.1.7 on 2021-04-09 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miniatures', '0009_auto_20210408_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamingSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='miniature',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='miniature',
            name='in_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='miniature',
            name='model_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='miniature',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='miniature',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='miniatures.gamingsystem'),
        ),
        migrations.DeleteModel(
            name='Manufacturer',
        ),
    ]
