# Generated by Django 3.1.7 on 2021-04-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniatures', '0012_auto_20210410_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='miniature',
            name='sku',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
