# Generated by Django 3.1.7 on 2021-04-10 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniatures', '0014_auto_20210410_1637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='army',
            options={'verbose_name_plural': 'Armies'},
        ),
    ]
