# Generated by Django 3.1.7 on 2021-04-11 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniatures', '0015_auto_20210410_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='miniature',
            old_name='gaming_system',
            new_name='gamesys',
        ),
        migrations.RenameField(
            model_name='miniature',
            old_name='model_count',
            new_name='itemcount',
        ),
        migrations.RenameField(
            model_name='miniature',
            old_name='in_stock',
            new_name='stock',
        ),
    ]
