# Generated by Django 3.1.7 on 2021-04-22 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniatures', '0018_auto_20210422_0727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='miniature',
            options={'ordering': ['gamesys', 'name']},
        ),
    ]
