# Generated by Django 3.1.7 on 2021-04-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='miniature_faction',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
